apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
  name: deployment
  namespace: bugtest
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deployment
    spec:
      containers:
      - args:
        - "9999"
        command:
        - sleep
        envFrom:
        - secretRef:
            name: shared-secret
        image: busybox:1.29.1
        imagePullPolicy: IfNotPresent
        name: main
      serviceAccountName: shared-sa
